### ISSUE TITLE
Simple MCP Test - 20250525081610

### ISSUE THREAD

**Issue by clemensv** [clemensv/xregistry-ai#17]
This is a simple test submission for the MCP workflow validation.

```yaml
repo: clemensv/xregistry-ai
path: test/mcp
branch: main
mcpprovider: test-provider
server: test-server
```

This issue will be automatically processed by the GitHub Actions workflow.
