### ISSUE TITLE
Simple A2A Test - 20250525091328

### ISSUE THREAD

**Issue by clemensv** [clemensv/xregistry-ai#28]
This is a simple test submission for the A2A workflow validation.

```yaml
repo: clemensv/xregistry-ai
path: test/a2a
branch: main
agentcardprovider: test-provider
agentcard: test-agentcard
```

This issue will be automatically processed by the GitHub Actions workflow.
